server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username:
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.PostgresSQLDialect
    database: postgresql
    defer-datasource-initialization: true
    database-platform:

  sql:
    init:
      mode: always

jwt:
  secret: E75Tee6NbFolxWF6UhUJvai4Kep2cZ/XVMazGJy8tLObS/MPRTElV4By0CN5t7Gic/NY78Hxz8Z5oXE4eeiN+Q==